/* 
 * The Giraf REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IWeekTemplateApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Deletes the template of the given ID.  Available to all Supers, and to Departments and Guardians of the same department as the template.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Id of the template that will be deleted.</param>
        /// <returns>Response</returns>
        Response V1WeekTemplateByIdDelete (long? id);

        /// <summary>
        /// Deletes the template of the given ID.  Available to all Supers, and to Departments and Guardians of the same department as the template.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Id of the template that will be deleted.</param>
        /// <returns>ApiResponse of Response</returns>
        ApiResponse<Response> V1WeekTemplateByIdDeleteWithHttpInfo (long? id);
        /// <summary>
        /// Gets the week template with the specified id.  Available to all users.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the week template to fetch.</param>
        /// <returns>ResponseWeekTemplateDTO</returns>
        ResponseWeekTemplateDTO V1WeekTemplateByIdGet (long? id);

        /// <summary>
        /// Gets the week template with the specified id.  Available to all users.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the week template to fetch.</param>
        /// <returns>ApiResponse of ResponseWeekTemplateDTO</returns>
        ApiResponse<ResponseWeekTemplateDTO> V1WeekTemplateByIdGetWithHttpInfo (long? id);
        /// <summary>
        /// Overwrite the information of a week template.  Available to all Supers, and to Departments and Guardians of the same department as the template.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Id of the template to overwrite.</param>
        /// <param name="newValuesDTO"> (optional)</param>
        /// <returns>ResponseWeekTemplateDTO</returns>
        ResponseWeekTemplateDTO V1WeekTemplateByIdPut (long? id, WeekTemplateDTO newValuesDTO = null);

        /// <summary>
        /// Overwrite the information of a week template.  Available to all Supers, and to Departments and Guardians of the same department as the template.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Id of the template to overwrite.</param>
        /// <param name="newValuesDTO"> (optional)</param>
        /// <returns>ApiResponse of ResponseWeekTemplateDTO</returns>
        ApiResponse<ResponseWeekTemplateDTO> V1WeekTemplateByIdPutWithHttpInfo (long? id, WeekTemplateDTO newValuesDTO = null);
        /// <summary>
        /// Gets all schedule templates for the currently authenticated user.  Available to all users.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ResponseIEnumerableWeekTemplateNameDTO</returns>
        ResponseIEnumerableWeekTemplateNameDTO V1WeekTemplateGet ();

        /// <summary>
        /// Gets all schedule templates for the currently authenticated user.  Available to all users.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of ResponseIEnumerableWeekTemplateNameDTO</returns>
        ApiResponse<ResponseIEnumerableWeekTemplateNameDTO> V1WeekTemplateGetWithHttpInfo ();
        /// <summary>
        /// Creates new week template in the department of the given user.   Available to Supers, Departments and Guardians.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="templateDTO">After successful execution, a new week template will be created with the same values as this DTO. (optional)</param>
        /// <returns>ResponseWeekTemplateDTO</returns>
        ResponseWeekTemplateDTO V1WeekTemplatePost (WeekTemplateDTO templateDTO = null);

        /// <summary>
        /// Creates new week template in the department of the given user.   Available to Supers, Departments and Guardians.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="templateDTO">After successful execution, a new week template will be created with the same values as this DTO. (optional)</param>
        /// <returns>ApiResponse of ResponseWeekTemplateDTO</returns>
        ApiResponse<ResponseWeekTemplateDTO> V1WeekTemplatePostWithHttpInfo (WeekTemplateDTO templateDTO = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Deletes the template of the given ID.  Available to all Supers, and to Departments and Guardians of the same department as the template.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Id of the template that will be deleted.</param>
        /// <returns>Task of Response</returns>
        System.Threading.Tasks.Task<Response> V1WeekTemplateByIdDeleteAsync (long? id);

        /// <summary>
        /// Deletes the template of the given ID.  Available to all Supers, and to Departments and Guardians of the same department as the template.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Id of the template that will be deleted.</param>
        /// <returns>Task of ApiResponse (Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<Response>> V1WeekTemplateByIdDeleteAsyncWithHttpInfo (long? id);
        /// <summary>
        /// Gets the week template with the specified id.  Available to all users.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the week template to fetch.</param>
        /// <returns>Task of ResponseWeekTemplateDTO</returns>
        System.Threading.Tasks.Task<ResponseWeekTemplateDTO> V1WeekTemplateByIdGetAsync (long? id);

        /// <summary>
        /// Gets the week template with the specified id.  Available to all users.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the week template to fetch.</param>
        /// <returns>Task of ApiResponse (ResponseWeekTemplateDTO)</returns>
        System.Threading.Tasks.Task<ApiResponse<ResponseWeekTemplateDTO>> V1WeekTemplateByIdGetAsyncWithHttpInfo (long? id);
        /// <summary>
        /// Overwrite the information of a week template.  Available to all Supers, and to Departments and Guardians of the same department as the template.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Id of the template to overwrite.</param>
        /// <param name="newValuesDTO"> (optional)</param>
        /// <returns>Task of ResponseWeekTemplateDTO</returns>
        System.Threading.Tasks.Task<ResponseWeekTemplateDTO> V1WeekTemplateByIdPutAsync (long? id, WeekTemplateDTO newValuesDTO = null);

        /// <summary>
        /// Overwrite the information of a week template.  Available to all Supers, and to Departments and Guardians of the same department as the template.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Id of the template to overwrite.</param>
        /// <param name="newValuesDTO"> (optional)</param>
        /// <returns>Task of ApiResponse (ResponseWeekTemplateDTO)</returns>
        System.Threading.Tasks.Task<ApiResponse<ResponseWeekTemplateDTO>> V1WeekTemplateByIdPutAsyncWithHttpInfo (long? id, WeekTemplateDTO newValuesDTO = null);
        /// <summary>
        /// Gets all schedule templates for the currently authenticated user.  Available to all users.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ResponseIEnumerableWeekTemplateNameDTO</returns>
        System.Threading.Tasks.Task<ResponseIEnumerableWeekTemplateNameDTO> V1WeekTemplateGetAsync ();

        /// <summary>
        /// Gets all schedule templates for the currently authenticated user.  Available to all users.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (ResponseIEnumerableWeekTemplateNameDTO)</returns>
        System.Threading.Tasks.Task<ApiResponse<ResponseIEnumerableWeekTemplateNameDTO>> V1WeekTemplateGetAsyncWithHttpInfo ();
        /// <summary>
        /// Creates new week template in the department of the given user.   Available to Supers, Departments and Guardians.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="templateDTO">After successful execution, a new week template will be created with the same values as this DTO. (optional)</param>
        /// <returns>Task of ResponseWeekTemplateDTO</returns>
        System.Threading.Tasks.Task<ResponseWeekTemplateDTO> V1WeekTemplatePostAsync (WeekTemplateDTO templateDTO = null);

        /// <summary>
        /// Creates new week template in the department of the given user.   Available to Supers, Departments and Guardians.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="templateDTO">After successful execution, a new week template will be created with the same values as this DTO. (optional)</param>
        /// <returns>Task of ApiResponse (ResponseWeekTemplateDTO)</returns>
        System.Threading.Tasks.Task<ApiResponse<ResponseWeekTemplateDTO>> V1WeekTemplatePostAsyncWithHttpInfo (WeekTemplateDTO templateDTO = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class WeekTemplateApi : IWeekTemplateApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="WeekTemplateApi"/> class.
        /// </summary>
        /// <returns></returns>
        public WeekTemplateApi(String basePath)
        {
            this.Configuration = new Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WeekTemplateApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public WeekTemplateApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Deletes the template of the given ID.  Available to all Supers, and to Departments and Guardians of the same department as the template. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Id of the template that will be deleted.</param>
        /// <returns>Response</returns>
        public Response V1WeekTemplateByIdDelete (long? id)
        {
             ApiResponse<Response> localVarResponse = V1WeekTemplateByIdDeleteWithHttpInfo(id);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Deletes the template of the given ID.  Available to all Supers, and to Departments and Guardians of the same department as the template. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Id of the template that will be deleted.</param>
        /// <returns>ApiResponse of Response</returns>
        public ApiResponse< Response > V1WeekTemplateByIdDeleteWithHttpInfo (long? id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling WeekTemplateApi->V1WeekTemplateByIdDelete");

            var localVarPath = "/v1/WeekTemplate/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", Configuration.ApiClient.ParameterToString(id)); // path parameter

            // authentication (Bearer) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V1WeekTemplateByIdDelete", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Response>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Response) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Response)));
        }

        /// <summary>
        /// Deletes the template of the given ID.  Available to all Supers, and to Departments and Guardians of the same department as the template. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Id of the template that will be deleted.</param>
        /// <returns>Task of Response</returns>
        public async System.Threading.Tasks.Task<Response> V1WeekTemplateByIdDeleteAsync (long? id)
        {
             ApiResponse<Response> localVarResponse = await V1WeekTemplateByIdDeleteAsyncWithHttpInfo(id);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Deletes the template of the given ID.  Available to all Supers, and to Departments and Guardians of the same department as the template. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Id of the template that will be deleted.</param>
        /// <returns>Task of ApiResponse (Response)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Response>> V1WeekTemplateByIdDeleteAsyncWithHttpInfo (long? id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling WeekTemplateApi->V1WeekTemplateByIdDelete");

            var localVarPath = "/v1/WeekTemplate/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", Configuration.ApiClient.ParameterToString(id)); // path parameter

            // authentication (Bearer) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V1WeekTemplateByIdDelete", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Response>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Response) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Response)));
        }

        /// <summary>
        /// Gets the week template with the specified id.  Available to all users. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the week template to fetch.</param>
        /// <returns>ResponseWeekTemplateDTO</returns>
        public ResponseWeekTemplateDTO V1WeekTemplateByIdGet (long? id)
        {
             ApiResponse<ResponseWeekTemplateDTO> localVarResponse = V1WeekTemplateByIdGetWithHttpInfo(id);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Gets the week template with the specified id.  Available to all users. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the week template to fetch.</param>
        /// <returns>ApiResponse of ResponseWeekTemplateDTO</returns>
        public ApiResponse< ResponseWeekTemplateDTO > V1WeekTemplateByIdGetWithHttpInfo (long? id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling WeekTemplateApi->V1WeekTemplateByIdGet");

            var localVarPath = "/v1/WeekTemplate/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", Configuration.ApiClient.ParameterToString(id)); // path parameter

            // authentication (Bearer) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V1WeekTemplateByIdGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ResponseWeekTemplateDTO>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ResponseWeekTemplateDTO) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ResponseWeekTemplateDTO)));
        }

        /// <summary>
        /// Gets the week template with the specified id.  Available to all users. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the week template to fetch.</param>
        /// <returns>Task of ResponseWeekTemplateDTO</returns>
        public async System.Threading.Tasks.Task<ResponseWeekTemplateDTO> V1WeekTemplateByIdGetAsync (long? id)
        {
             ApiResponse<ResponseWeekTemplateDTO> localVarResponse = await V1WeekTemplateByIdGetAsyncWithHttpInfo(id);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Gets the week template with the specified id.  Available to all users. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the week template to fetch.</param>
        /// <returns>Task of ApiResponse (ResponseWeekTemplateDTO)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ResponseWeekTemplateDTO>> V1WeekTemplateByIdGetAsyncWithHttpInfo (long? id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling WeekTemplateApi->V1WeekTemplateByIdGet");

            var localVarPath = "/v1/WeekTemplate/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", Configuration.ApiClient.ParameterToString(id)); // path parameter

            // authentication (Bearer) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V1WeekTemplateByIdGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ResponseWeekTemplateDTO>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ResponseWeekTemplateDTO) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ResponseWeekTemplateDTO)));
        }

        /// <summary>
        /// Overwrite the information of a week template.  Available to all Supers, and to Departments and Guardians of the same department as the template. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Id of the template to overwrite.</param>
        /// <param name="newValuesDTO"> (optional)</param>
        /// <returns>ResponseWeekTemplateDTO</returns>
        public ResponseWeekTemplateDTO V1WeekTemplateByIdPut (long? id, WeekTemplateDTO newValuesDTO = null)
        {
             ApiResponse<ResponseWeekTemplateDTO> localVarResponse = V1WeekTemplateByIdPutWithHttpInfo(id, newValuesDTO);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Overwrite the information of a week template.  Available to all Supers, and to Departments and Guardians of the same department as the template. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Id of the template to overwrite.</param>
        /// <param name="newValuesDTO"> (optional)</param>
        /// <returns>ApiResponse of ResponseWeekTemplateDTO</returns>
        public ApiResponse< ResponseWeekTemplateDTO > V1WeekTemplateByIdPutWithHttpInfo (long? id, WeekTemplateDTO newValuesDTO = null)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling WeekTemplateApi->V1WeekTemplateByIdPut");

            var localVarPath = "/v1/WeekTemplate/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (newValuesDTO != null && newValuesDTO.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(newValuesDTO); // http body (model) parameter
            }
            else
            {
                localVarPostBody = newValuesDTO; // byte array
            }

            // authentication (Bearer) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V1WeekTemplateByIdPut", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ResponseWeekTemplateDTO>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ResponseWeekTemplateDTO) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ResponseWeekTemplateDTO)));
        }

        /// <summary>
        /// Overwrite the information of a week template.  Available to all Supers, and to Departments and Guardians of the same department as the template. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Id of the template to overwrite.</param>
        /// <param name="newValuesDTO"> (optional)</param>
        /// <returns>Task of ResponseWeekTemplateDTO</returns>
        public async System.Threading.Tasks.Task<ResponseWeekTemplateDTO> V1WeekTemplateByIdPutAsync (long? id, WeekTemplateDTO newValuesDTO = null)
        {
             ApiResponse<ResponseWeekTemplateDTO> localVarResponse = await V1WeekTemplateByIdPutAsyncWithHttpInfo(id, newValuesDTO);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Overwrite the information of a week template.  Available to all Supers, and to Departments and Guardians of the same department as the template. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Id of the template to overwrite.</param>
        /// <param name="newValuesDTO"> (optional)</param>
        /// <returns>Task of ApiResponse (ResponseWeekTemplateDTO)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ResponseWeekTemplateDTO>> V1WeekTemplateByIdPutAsyncWithHttpInfo (long? id, WeekTemplateDTO newValuesDTO = null)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling WeekTemplateApi->V1WeekTemplateByIdPut");

            var localVarPath = "/v1/WeekTemplate/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (newValuesDTO != null && newValuesDTO.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(newValuesDTO); // http body (model) parameter
            }
            else
            {
                localVarPostBody = newValuesDTO; // byte array
            }

            // authentication (Bearer) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V1WeekTemplateByIdPut", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ResponseWeekTemplateDTO>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ResponseWeekTemplateDTO) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ResponseWeekTemplateDTO)));
        }

        /// <summary>
        /// Gets all schedule templates for the currently authenticated user.  Available to all users. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ResponseIEnumerableWeekTemplateNameDTO</returns>
        public ResponseIEnumerableWeekTemplateNameDTO V1WeekTemplateGet ()
        {
             ApiResponse<ResponseIEnumerableWeekTemplateNameDTO> localVarResponse = V1WeekTemplateGetWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// Gets all schedule templates for the currently authenticated user.  Available to all users. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of ResponseIEnumerableWeekTemplateNameDTO</returns>
        public ApiResponse< ResponseIEnumerableWeekTemplateNameDTO > V1WeekTemplateGetWithHttpInfo ()
        {

            var localVarPath = "/v1/WeekTemplate";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // authentication (Bearer) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V1WeekTemplateGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ResponseIEnumerableWeekTemplateNameDTO>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ResponseIEnumerableWeekTemplateNameDTO) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ResponseIEnumerableWeekTemplateNameDTO)));
        }

        /// <summary>
        /// Gets all schedule templates for the currently authenticated user.  Available to all users. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ResponseIEnumerableWeekTemplateNameDTO</returns>
        public async System.Threading.Tasks.Task<ResponseIEnumerableWeekTemplateNameDTO> V1WeekTemplateGetAsync ()
        {
             ApiResponse<ResponseIEnumerableWeekTemplateNameDTO> localVarResponse = await V1WeekTemplateGetAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        /// Gets all schedule templates for the currently authenticated user.  Available to all users. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (ResponseIEnumerableWeekTemplateNameDTO)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ResponseIEnumerableWeekTemplateNameDTO>> V1WeekTemplateGetAsyncWithHttpInfo ()
        {

            var localVarPath = "/v1/WeekTemplate";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // authentication (Bearer) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V1WeekTemplateGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ResponseIEnumerableWeekTemplateNameDTO>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ResponseIEnumerableWeekTemplateNameDTO) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ResponseIEnumerableWeekTemplateNameDTO)));
        }

        /// <summary>
        /// Creates new week template in the department of the given user.   Available to Supers, Departments and Guardians. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="templateDTO">After successful execution, a new week template will be created with the same values as this DTO. (optional)</param>
        /// <returns>ResponseWeekTemplateDTO</returns>
        public ResponseWeekTemplateDTO V1WeekTemplatePost (WeekTemplateDTO templateDTO = null)
        {
             ApiResponse<ResponseWeekTemplateDTO> localVarResponse = V1WeekTemplatePostWithHttpInfo(templateDTO);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Creates new week template in the department of the given user.   Available to Supers, Departments and Guardians. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="templateDTO">After successful execution, a new week template will be created with the same values as this DTO. (optional)</param>
        /// <returns>ApiResponse of ResponseWeekTemplateDTO</returns>
        public ApiResponse< ResponseWeekTemplateDTO > V1WeekTemplatePostWithHttpInfo (WeekTemplateDTO templateDTO = null)
        {

            var localVarPath = "/v1/WeekTemplate";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (templateDTO != null && templateDTO.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(templateDTO); // http body (model) parameter
            }
            else
            {
                localVarPostBody = templateDTO; // byte array
            }

            // authentication (Bearer) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V1WeekTemplatePost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ResponseWeekTemplateDTO>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ResponseWeekTemplateDTO) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ResponseWeekTemplateDTO)));
        }

        /// <summary>
        /// Creates new week template in the department of the given user.   Available to Supers, Departments and Guardians. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="templateDTO">After successful execution, a new week template will be created with the same values as this DTO. (optional)</param>
        /// <returns>Task of ResponseWeekTemplateDTO</returns>
        public async System.Threading.Tasks.Task<ResponseWeekTemplateDTO> V1WeekTemplatePostAsync (WeekTemplateDTO templateDTO = null)
        {
             ApiResponse<ResponseWeekTemplateDTO> localVarResponse = await V1WeekTemplatePostAsyncWithHttpInfo(templateDTO);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Creates new week template in the department of the given user.   Available to Supers, Departments and Guardians. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="templateDTO">After successful execution, a new week template will be created with the same values as this DTO. (optional)</param>
        /// <returns>Task of ApiResponse (ResponseWeekTemplateDTO)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ResponseWeekTemplateDTO>> V1WeekTemplatePostAsyncWithHttpInfo (WeekTemplateDTO templateDTO = null)
        {

            var localVarPath = "/v1/WeekTemplate";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (templateDTO != null && templateDTO.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(templateDTO); // http body (model) parameter
            }
            else
            {
                localVarPostBody = templateDTO; // byte array
            }

            // authentication (Bearer) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V1WeekTemplatePost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ResponseWeekTemplateDTO>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ResponseWeekTemplateDTO) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ResponseWeekTemplateDTO)));
        }

    }
}
