/* 
 * My API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ChoiceApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ChoiceApiTests
    {
        private ChoiceApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ChoiceApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ChoiceApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ChoiceApi
            //Assert.IsInstanceOfType(typeof(ChoiceApi), instance, "instance is a ChoiceApi");
        }

        
        /// <summary>
        /// Test V1ChoiceByIdDelete
        /// </summary>
        [Test]
        public void V1ChoiceByIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? id = null;
            //var response = instance.V1ChoiceByIdDelete(id);
            //Assert.IsInstanceOf<Response> (response, "response is Response");
        }
        
        /// <summary>
        /// Test V1ChoiceByIdGet
        /// </summary>
        [Test]
        public void V1ChoiceByIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? id = null;
            //var response = instance.V1ChoiceByIdGet(id);
            //Assert.IsInstanceOf<ResponseChoiceDTO> (response, "response is ResponseChoiceDTO");
        }
        
        /// <summary>
        /// Test V1ChoiceByIdPut
        /// </summary>
        [Test]
        public void V1ChoiceByIdPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? id = null;
            //ChoiceDTO newValues = null;
            //var response = instance.V1ChoiceByIdPut(id, newValues);
            //Assert.IsInstanceOf<ResponseChoiceDTO> (response, "response is ResponseChoiceDTO");
        }
        
        /// <summary>
        /// Test V1ChoicePost
        /// </summary>
        [Test]
        public void V1ChoicePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ChoiceDTO choice = null;
            //var response = instance.V1ChoicePost(choice);
            //Assert.IsInstanceOf<ResponseChoiceDTO> (response, "response is ResponseChoiceDTO");
        }
        
    }

}
