/* 
 * My API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing StatusApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class StatusApiTests
    {
        private StatusApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new StatusApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StatusApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' StatusApi
            //Assert.IsInstanceOfType(typeof(StatusApi), instance, "instance is a StatusApi");
        }

        
        /// <summary>
        /// Test V1StatusDatabaseGet
        /// </summary>
        [Test]
        public void V1StatusDatabaseGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.V1StatusDatabaseGet();
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
        /// <summary>
        /// Test V1StatusGet
        /// </summary>
        [Test]
        public void V1StatusGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.V1StatusGet();
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
    }

}
