/* 
 * The Giraf REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// WeekNameDTO
    /// </summary>
    [DataContract]
    public partial class WeekNameDTO :  IEquatable<WeekNameDTO>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WeekNameDTO" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        public WeekNameDTO()
        {
        }
        
        /// <summary>
        /// A Name describing the week.
        /// </summary>
        /// <value>A Name describing the week.</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; private set; }

        /// <summary>
        /// The year of the week.
        /// </summary>
        /// <value>The year of the week.</value>
        [DataMember(Name="weekYear", EmitDefaultValue=false)]
        public int? WeekYear { get; private set; }

        /// <summary>
        /// The number of the week, 0 - 52 (53).
        /// </summary>
        /// <value>The number of the week, 0 - 52 (53).</value>
        [DataMember(Name="weekNumber", EmitDefaultValue=false)]
        public int? WeekNumber { get; private set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class WeekNameDTO {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  WeekYear: ").Append(WeekYear).Append("\n");
            sb.Append("  WeekNumber: ").Append(WeekNumber).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as WeekNameDTO);
        }

        /// <summary>
        /// Returns true if WeekNameDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of WeekNameDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(WeekNameDTO input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.WeekYear == input.WeekYear ||
                    (this.WeekYear != null &&
                    this.WeekYear.Equals(input.WeekYear))
                ) && 
                (
                    this.WeekNumber == input.WeekNumber ||
                    (this.WeekNumber != null &&
                    this.WeekNumber.Equals(input.WeekNumber))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.WeekYear != null)
                    hashCode = hashCode * 59 + this.WeekYear.GetHashCode();
                if (this.WeekNumber != null)
                    hashCode = hashCode * 59 + this.WeekNumber.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
