/* 
 * My API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing GirafUserDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GirafUserDTOTests
    {
        // TODO uncomment below to declare an instance variable for GirafUserDTO
        //private GirafUserDTO instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GirafUserDTO
            //instance = new GirafUserDTO();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GirafUserDTO
        /// </summary>
        [Test]
        public void GirafUserDTOInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GirafUserDTO
            //Assert.IsInstanceOfType<GirafUserDTO> (instance, "variable 'instance' is a GirafUserDTO");
        }


        /// <summary>
        /// Test the property 'Role'
        /// </summary>
        [Test]
        public void RoleTest()
        {
            // TODO unit test for the property 'Role'
        }
        /// <summary>
        /// Test the property 'RoleName'
        /// </summary>
        [Test]
        public void RoleNameTest()
        {
            // TODO unit test for the property 'RoleName'
        }
        /// <summary>
        /// Test the property 'Citizens'
        /// </summary>
        [Test]
        public void CitizensTest()
        {
            // TODO unit test for the property 'Citizens'
        }
        /// <summary>
        /// Test the property 'Guardians'
        /// </summary>
        [Test]
        public void GuardiansTest()
        {
            // TODO unit test for the property 'Guardians'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Test]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }
        /// <summary>
        /// Test the property 'ScreenName'
        /// </summary>
        [Test]
        public void ScreenNameTest()
        {
            // TODO unit test for the property 'ScreenName'
        }
        /// <summary>
        /// Test the property 'UserIcon'
        /// </summary>
        [Test]
        public void UserIconTest()
        {
            // TODO unit test for the property 'UserIcon'
        }
        /// <summary>
        /// Test the property 'Department'
        /// </summary>
        [Test]
        public void DepartmentTest()
        {
            // TODO unit test for the property 'Department'
        }
        /// <summary>
        /// Test the property 'WeekScheduleIds'
        /// </summary>
        [Test]
        public void WeekScheduleIdsTest()
        {
            // TODO unit test for the property 'WeekScheduleIds'
        }
        /// <summary>
        /// Test the property 'Resources'
        /// </summary>
        [Test]
        public void ResourcesTest()
        {
            // TODO unit test for the property 'Resources'
        }
        /// <summary>
        /// Test the property 'Settings'
        /// </summary>
        [Test]
        public void SettingsTest()
        {
            // TODO unit test for the property 'Settings'
        }

    }

}
