/* 
 * My API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing LauncherOptions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LauncherOptionsTests
    {
        // TODO uncomment below to declare an instance variable for LauncherOptions
        //private LauncherOptions instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LauncherOptions
            //instance = new LauncherOptions();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LauncherOptions
        /// </summary>
        [Test]
        public void LauncherOptionsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LauncherOptions
            //Assert.IsInstanceOfType<LauncherOptions> (instance, "variable 'instance' is a LauncherOptions");
        }


        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Test]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }
        /// <summary>
        /// Test the property 'UseGrayscale'
        /// </summary>
        [Test]
        public void UseGrayscaleTest()
        {
            // TODO unit test for the property 'UseGrayscale'
        }
        /// <summary>
        /// Test the property 'DisplayLauncherAnimations'
        /// </summary>
        [Test]
        public void DisplayLauncherAnimationsTest()
        {
            // TODO unit test for the property 'DisplayLauncherAnimations'
        }
        /// <summary>
        /// Test the property 'AppsUserCanAccess'
        /// </summary>
        [Test]
        public void AppsUserCanAccessTest()
        {
            // TODO unit test for the property 'AppsUserCanAccess'
        }
        /// <summary>
        /// Test the property 'AppGridSizeRows'
        /// </summary>
        [Test]
        public void AppGridSizeRowsTest()
        {
            // TODO unit test for the property 'AppGridSizeRows'
        }
        /// <summary>
        /// Test the property 'AppGridSizeColumns'
        /// </summary>
        [Test]
        public void AppGridSizeColumnsTest()
        {
            // TODO unit test for the property 'AppGridSizeColumns'
        }

    }

}
