/* 
 * My API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ResponseLauncherOptions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ResponseLauncherOptionsTests
    {
        // TODO uncomment below to declare an instance variable for ResponseLauncherOptions
        //private ResponseLauncherOptions instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ResponseLauncherOptions
            //instance = new ResponseLauncherOptions();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ResponseLauncherOptions
        /// </summary>
        [Test]
        public void ResponseLauncherOptionsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ResponseLauncherOptions
            //Assert.IsInstanceOfType<ResponseLauncherOptions> (instance, "variable 'instance' is a ResponseLauncherOptions");
        }


        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Test]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Test]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }
        /// <summary>
        /// Test the property 'ErrorProperties'
        /// </summary>
        [Test]
        public void ErrorPropertiesTest()
        {
            // TODO unit test for the property 'ErrorProperties'
        }
        /// <summary>
        /// Test the property 'ErrorKey'
        /// </summary>
        [Test]
        public void ErrorKeyTest()
        {
            // TODO unit test for the property 'ErrorKey'
        }

    }

}
