/* 
 * My API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing WeekdayDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WeekdayDTOTests
    {
        // TODO uncomment below to declare an instance variable for WeekdayDTO
        //private WeekdayDTO instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WeekdayDTO
            //instance = new WeekdayDTO();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WeekdayDTO
        /// </summary>
        [Test]
        public void WeekdayDTOInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WeekdayDTO
            //Assert.IsInstanceOfType<WeekdayDTO> (instance, "variable 'instance' is a WeekdayDTO");
        }


        /// <summary>
        /// Test the property 'ElementIDs'
        /// </summary>
        [Test]
        public void ElementIDsTest()
        {
            // TODO unit test for the property 'ElementIDs'
        }
        /// <summary>
        /// Test the property 'Day'
        /// </summary>
        [Test]
        public void DayTest()
        {
            // TODO unit test for the property 'Day'
        }
        /// <summary>
        /// Test the property 'Elements'
        /// </summary>
        [Test]
        public void ElementsTest()
        {
            // TODO unit test for the property 'Elements'
        }

    }

}
