// Mocks generated by Mockito 5.4.6 from annotations
// in weekplanner/test/features/auth/auth_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:weekplanner/shared/models/activity.dart' as _i6;
import 'package:weekplanner/shared/models/citizen.dart' as _i9;
import 'package:weekplanner/shared/models/grade.dart' as _i10;
import 'package:weekplanner/shared/models/organisation.dart' as _i4;
import 'package:weekplanner/shared/models/paginated_response.dart' as _i3;
import 'package:weekplanner/shared/models/pictogram.dart' as _i5;
import 'package:weekplanner/shared/services/activity_api_service.dart' as _i11;
import 'package:weekplanner/shared/services/auth_service.dart' as _i2;
import 'package:weekplanner/shared/services/core_api_service.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthTokens_0 extends _i1.SmartFake implements _i2.AuthTokens {
  _FakeAuthTokens_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePaginatedResponse_1<T> extends _i1.SmartFake
    implements _i3.PaginatedResponse<T> {
  _FakePaginatedResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrganisation_2 extends _i1.SmartFake implements _i4.Organisation {
  _FakeOrganisation_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePictogram_3 extends _i1.SmartFake implements _i5.Pictogram {
  _FakePictogram_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeActivity_4 extends _i1.SmartFake implements _i6.Activity {
  _FakeActivity_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i2.AuthService {
  @override
  _i7.Future<_i2.AuthTokens> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i7.Future<_i2.AuthTokens>.value(
              _FakeAuthTokens_0(
                this,
                Invocation.method(#login, [email, password]),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i2.AuthTokens>.value(
              _FakeAuthTokens_0(
                this,
                Invocation.method(#login, [email, password]),
              ),
            ),
          )
          as _i7.Future<_i2.AuthTokens>);

  @override
  _i7.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<String?> getStoredAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#getStoredAccessToken, []),
            returnValue: _i7.Future<String?>.value(),
            returnValueForMissingStub: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<String?> getStoredRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#getStoredRefreshToken, []),
            returnValue: _i7.Future<String?>.value(),
            returnValueForMissingStub: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<void> saveCredentials(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#saveCredentials, [email, password]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<({String? email, String? password})> getSavedCredentials() =>
      (super.noSuchMethod(
            Invocation.method(#getSavedCredentials, []),
            returnValue: _i7.Future<({String? email, String? password})>.value((
              email: null,
              password: null,
            )),
            returnValueForMissingStub:
                _i7.Future<({String? email, String? password})>.value((
                  email: null,
                  password: null,
                )),
          )
          as _i7.Future<({String? email, String? password})>);

  @override
  _i7.Future<void> clearSavedCredentials() =>
      (super.noSuchMethod(
            Invocation.method(#clearSavedCredentials, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [CoreApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCoreApiService extends _i1.Mock implements _i8.CoreApiService {
  @override
  void setAuthToken(String? token) => super.noSuchMethod(
    Invocation.method(#setAuthToken, [token]),
    returnValueForMissingStub: null,
  );

  @override
  void clearAuthToken() => super.noSuchMethod(
    Invocation.method(#clearAuthToken, []),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<_i3.PaginatedResponse<_i4.Organisation>> fetchOrganisations() =>
      (super.noSuchMethod(
            Invocation.method(#fetchOrganisations, []),
            returnValue:
                _i7.Future<_i3.PaginatedResponse<_i4.Organisation>>.value(
                  _FakePaginatedResponse_1<_i4.Organisation>(
                    this,
                    Invocation.method(#fetchOrganisations, []),
                  ),
                ),
            returnValueForMissingStub:
                _i7.Future<_i3.PaginatedResponse<_i4.Organisation>>.value(
                  _FakePaginatedResponse_1<_i4.Organisation>(
                    this,
                    Invocation.method(#fetchOrganisations, []),
                  ),
                ),
          )
          as _i7.Future<_i3.PaginatedResponse<_i4.Organisation>>);

  @override
  _i7.Future<_i4.Organisation> fetchOrganisation(int? orgId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchOrganisation, [orgId]),
            returnValue: _i7.Future<_i4.Organisation>.value(
              _FakeOrganisation_2(
                this,
                Invocation.method(#fetchOrganisation, [orgId]),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i4.Organisation>.value(
              _FakeOrganisation_2(
                this,
                Invocation.method(#fetchOrganisation, [orgId]),
              ),
            ),
          )
          as _i7.Future<_i4.Organisation>);

  @override
  _i7.Future<_i3.PaginatedResponse<_i9.Citizen>> fetchCitizens(int? orgId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCitizens, [orgId]),
            returnValue: _i7.Future<_i3.PaginatedResponse<_i9.Citizen>>.value(
              _FakePaginatedResponse_1<_i9.Citizen>(
                this,
                Invocation.method(#fetchCitizens, [orgId]),
              ),
            ),
            returnValueForMissingStub:
                _i7.Future<_i3.PaginatedResponse<_i9.Citizen>>.value(
                  _FakePaginatedResponse_1<_i9.Citizen>(
                    this,
                    Invocation.method(#fetchCitizens, [orgId]),
                  ),
                ),
          )
          as _i7.Future<_i3.PaginatedResponse<_i9.Citizen>>);

  @override
  _i7.Future<_i3.PaginatedResponse<_i10.Grade>> fetchGrades(int? orgId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchGrades, [orgId]),
            returnValue: _i7.Future<_i3.PaginatedResponse<_i10.Grade>>.value(
              _FakePaginatedResponse_1<_i10.Grade>(
                this,
                Invocation.method(#fetchGrades, [orgId]),
              ),
            ),
            returnValueForMissingStub:
                _i7.Future<_i3.PaginatedResponse<_i10.Grade>>.value(
                  _FakePaginatedResponse_1<_i10.Grade>(
                    this,
                    Invocation.method(#fetchGrades, [orgId]),
                  ),
                ),
          )
          as _i7.Future<_i3.PaginatedResponse<_i10.Grade>>);

  @override
  _i7.Future<_i3.PaginatedResponse<_i5.Pictogram>> searchPictograms({
    String? query,
    int? limit = 20,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchPictograms, [], {
              #query: query,
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i7.Future<_i3.PaginatedResponse<_i5.Pictogram>>.value(
              _FakePaginatedResponse_1<_i5.Pictogram>(
                this,
                Invocation.method(#searchPictograms, [], {
                  #query: query,
                  #limit: limit,
                  #offset: offset,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i7.Future<_i3.PaginatedResponse<_i5.Pictogram>>.value(
                  _FakePaginatedResponse_1<_i5.Pictogram>(
                    this,
                    Invocation.method(#searchPictograms, [], {
                      #query: query,
                      #limit: limit,
                      #offset: offset,
                    }),
                  ),
                ),
          )
          as _i7.Future<_i3.PaginatedResponse<_i5.Pictogram>>);

  @override
  _i7.Future<_i5.Pictogram> fetchPictogram(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchPictogram, [id]),
            returnValue: _i7.Future<_i5.Pictogram>.value(
              _FakePictogram_3(this, Invocation.method(#fetchPictogram, [id])),
            ),
            returnValueForMissingStub: _i7.Future<_i5.Pictogram>.value(
              _FakePictogram_3(this, Invocation.method(#fetchPictogram, [id])),
            ),
          )
          as _i7.Future<_i5.Pictogram>);
}

/// A class which mocks [ActivityApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockActivityApiService extends _i1.Mock
    implements _i11.ActivityApiService {
  @override
  void setAuthToken(String? token) => super.noSuchMethod(
    Invocation.method(#setAuthToken, [token]),
    returnValueForMissingStub: null,
  );

  @override
  void clearAuthToken() => super.noSuchMethod(
    Invocation.method(#clearAuthToken, []),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<List<_i6.Activity>> fetchActivitiesByCitizen(
    int? citizenId,
    String? date,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchActivitiesByCitizen, [citizenId, date]),
            returnValue: _i7.Future<List<_i6.Activity>>.value(<_i6.Activity>[]),
            returnValueForMissingStub: _i7.Future<List<_i6.Activity>>.value(
              <_i6.Activity>[],
            ),
          )
          as _i7.Future<List<_i6.Activity>>);

  @override
  _i7.Future<List<_i6.Activity>> fetchActivitiesByGrade(
    int? gradeId,
    String? date,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchActivitiesByGrade, [gradeId, date]),
            returnValue: _i7.Future<List<_i6.Activity>>.value(<_i6.Activity>[]),
            returnValueForMissingStub: _i7.Future<List<_i6.Activity>>.value(
              <_i6.Activity>[],
            ),
          )
          as _i7.Future<List<_i6.Activity>>);

  @override
  _i7.Future<_i6.Activity> fetchActivity(int? activityId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchActivity, [activityId]),
            returnValue: _i7.Future<_i6.Activity>.value(
              _FakeActivity_4(
                this,
                Invocation.method(#fetchActivity, [activityId]),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i6.Activity>.value(
              _FakeActivity_4(
                this,
                Invocation.method(#fetchActivity, [activityId]),
              ),
            ),
          )
          as _i7.Future<_i6.Activity>);

  @override
  _i7.Future<_i6.Activity> createActivityForCitizen(
    int? citizenId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createActivityForCitizen, [citizenId, data]),
            returnValue: _i7.Future<_i6.Activity>.value(
              _FakeActivity_4(
                this,
                Invocation.method(#createActivityForCitizen, [citizenId, data]),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i6.Activity>.value(
              _FakeActivity_4(
                this,
                Invocation.method(#createActivityForCitizen, [citizenId, data]),
              ),
            ),
          )
          as _i7.Future<_i6.Activity>);

  @override
  _i7.Future<_i6.Activity> createActivityForGrade(
    int? gradeId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createActivityForGrade, [gradeId, data]),
            returnValue: _i7.Future<_i6.Activity>.value(
              _FakeActivity_4(
                this,
                Invocation.method(#createActivityForGrade, [gradeId, data]),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i6.Activity>.value(
              _FakeActivity_4(
                this,
                Invocation.method(#createActivityForGrade, [gradeId, data]),
              ),
            ),
          )
          as _i7.Future<_i6.Activity>);

  @override
  _i7.Future<_i6.Activity> updateActivity(
    int? activityId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateActivity, [activityId, data]),
            returnValue: _i7.Future<_i6.Activity>.value(
              _FakeActivity_4(
                this,
                Invocation.method(#updateActivity, [activityId, data]),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i6.Activity>.value(
              _FakeActivity_4(
                this,
                Invocation.method(#updateActivity, [activityId, data]),
              ),
            ),
          )
          as _i7.Future<_i6.Activity>);

  @override
  _i7.Future<void> deleteActivity(int? activityId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteActivity, [activityId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i6.Activity> toggleActivityStatus(int? activityId) =>
      (super.noSuchMethod(
            Invocation.method(#toggleActivityStatus, [activityId]),
            returnValue: _i7.Future<_i6.Activity>.value(
              _FakeActivity_4(
                this,
                Invocation.method(#toggleActivityStatus, [activityId]),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i6.Activity>.value(
              _FakeActivity_4(
                this,
                Invocation.method(#toggleActivityStatus, [activityId]),
              ),
            ),
          )
          as _i7.Future<_i6.Activity>);
}
